insertion sort code
iiitv/algos pull request #742
Opened 2020-08-31 16:45 UTC by nlok5923

Fixes #691 

#### By submitting this pull request I confirm I've read and complied with the below declarations.

- [x] I have read the [Contribution guidelines](https://github.com/iiitv/algos/blob/master/CONTRIBUTING.md) and I am confident that my PR reflects them.
- [x] I have followed the [coding guidelines](https://github.com/iiitv/algos/blob/master/CONTRIBUTING.md#cs) for this project.
- [x] My code follows the [skeleton code structure](https://github.com/iiitv/algos/blob/master/CONTRIBUTING.md#sample).
- [x] This pull request has a descriptive title. For example, `Added {Algorithm/DS name} [{Language}]`, not `Update README.md` or `Added new code`.
- [x] This pull request will be closed if I fail to update it even once in a continuous time span of 7 days.
- [x] This pull request shall only be reviewed and merged once the Travis build passes. No maintainer or supporter shall be obliged to review it before this condition is met.
- [x] I have mentioned the issue number correctly (with hyperlink) in this pull request description.

2020-09-06 05:28 UTC, ishanksoni approved these changes
LGTM

2020-09-26 18:05 UTC, yashshah2820 commented on insertion_sort/insertion_sort.cpp
> +	int array[] = {5, 4, 233, 32, 1, 4, 34, 3, 23};
make this a user input driven implementation

2020-09-26 18:06 UTC, nlok5923 commented
@yashshah2820 okay sir working on it.

2020-09-26 18:06 UTC, yashshah2820 requested changes

2020-09-26 18:06 UTC, yashshah2820 commented on insertion_sort/insertion_sort.cpp
> +	int array[] = {5, 4, 233, 32, 1, 4, 34, 3, 23};
make this a user input driven implementation

2020-09-26 18:15 UTC, nlok5923 commented
@yashshah2820 done changes : 
![Screenshot (1374)](https://user-images.githubusercontent.com/56120084/94347482-83af7b80-ffe9-11ea-81ad-69516cc15384.png)

2020-09-26 18:24 UTC, yashshah2820 approved these changes

2020-09-26 18:24 UTC, merged